name: Check Python formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install isort and black
        run: pip install isort black

      - name: Run isort
        run: isort --check-only --diff bin.src/ python/ tests/

      - name: Run black
        run: black --check --verbose --diff bin.src/* python/ tests/
